org: gabrieloliveira
app: graphql-pt1
service: graphql-pt1

frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
